name: CI / Integration Tests

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
       os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install prerequisites (libgtk on ubuntu)
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libgtk2.0-0 
        fi
      shell: bash
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 clean package -P integrationtests --file pom.xml
